### ISSUE TITLE
activate environment

### ISSUE THREAD

**Issue by djbears32** [SinfulPhantom/discord_bot_template#1]
Had issues on windows activating virtual environment
3. Activate the Virtual Environment
On Windows using Command Prompt:

cmd
Copy code
venv\Scripts\activate.bat
On Windows using PowerShell:

powershell
Copy code
.\venv\Scripts\Activate.ps1
If you encounter permissions issues, you might need to adjust the execution policy with the command provided in a previous response, then try the activation command again.

On Unix-like systems (Linux, macOS):

bash
Copy code
source venv/bin/activate

**Comment by djbears32** [comment]
this is what i had to do guess the read me just needs to be updated

**Comment by SinfulPhantom** [comment]
This has been merged in #2 
Thanks!
